api/urls.py
from django.contrib import admin
from django.urls import include, path
from blog_app.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'api'

urlpatterns = (
        [
            path('articles/<int:pk>', ArticleDetailView.as_view(), name='article_api'),
            path('articles/', ArticleListView.as_view(), name='articles_api'),
            path('products/', ProductListApiView.as_view(), name='products_api'),
        ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

blog_app/urls.py
from django.contrib import admin
from django.urls import include, path
from blog_app.views import *
from django.conf import settings
from django.conf.urls.static import static
from .views import CreateArticleView, ArticleListView, ArticleDetailView, ArticleThemeListView, UpdateArticleView

app_name = 'blog_app'

urlpatterns = [
                  path('update_article/<int:pk>/', UpdateArticleView.as_view(), name='update_article'),
                  path('theme/<slug:slug>/', ArticleThemeListView.as_view(), name='theme'),
                  path('create_article/', CreateArticleView.as_view(), name='create_article'),
                  path('', ArticleListView.as_view(), name='blog'),
                  path('<slug:slug>/', ArticleDetailView.as_view(), name='article'),

              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_store_app/urls.py
from django.contrib import admin
from django.urls import include, path
from my_store_app.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
    [
        path("", CategoryView.as_view(), name="index"),
        path("catalog/filter/", product_filter, name="product_filter"),
        path("catalog/", CatalogView.as_view(), name="catalog"),
        path(
            "catalog/<slug:category_slug>/",
            CategoryDetailView.as_view(),
            name="category",
        ),
        path("catalog/tags/<int:tag_id>/", TagPageView.as_view(), name="tag_page"),
        path(
            "catalog/product/<slug:product_slug>/",
            ProductDetailView.as_view(),
            name="product",
        ),
        path("search/", search, name="search"),
        path("about/", AboutUsView.as_view(), name="about"),
        path("api/", api_view, name="api"),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

online_store/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from my_store_app.views import *
from profile_app.views import *
from order_app.views import *
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("admin/", admin.site.urls),
    path("", include("my_store_app.urls")),
    path("", include("profile_app.urls")),
    path("", include("order_app.urls")),
    path("blog/", include("blog_app.urls")),
    path("api/", include("api.urls")),

]

api/models.py
from django.db import models

# Create your models here.

my_store_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from rest_framework.exceptions import ValidationError
from django.utils.text import slugify
import uuid
from django.utils import timezone


def create_image_path_for_product(instance, filename):
    return "upload/products/product_{pk}/{filename}".format(
        pk=instance.pk, filename=filename
    )


def create_image_path_for_product_gallery(instance, filename):
    return "upload/products/gallery/{filename}".format(filename=filename)


def create_image_path_for_category(instance, filename):
    if instance.pk:
        return f"upload/categories/categoryproduct_{instance.pk}/{filename}"
    else:
        uuid_str = uuid.uuid4().hex
        return f"upload/categories/categoryproduct_{str(uuid.uuid4())}/{filename}"


def create_image_path_for_profile(instance, filename):
    return "upload/profiles/profile_{pk}/{filename}".format(
        pk=instance.pk, filename=filename
    )


class Profile(models.Model):
    def validate_image(fieldfile_obj):
        file_size = fieldfile_obj.file.size
        megabyte_limit = 150.0
        if file_size > megabyte_limit * 1024 * 1024:
            raise ValidationError(
                "Максимальный размер файла {}MB".format(str(megabyte_limit))
            )

    user = models.OneToOneField(
        User, unique=True, on_delete=models.CASCADE, related_name="profile"
    )
    username = models.CharField(
        default="-------",
        max_length=50,
        verbose_name="username",
        blank=True,
        null=True,
        unique=False,
    )
    full_name = models.CharField(
        default="не указано", max_length=50, verbose_name="ФИО пользователя", blank=True
    )
    phone = models.CharField(
        default="Не указано",
        max_length=30,
        verbose_name="номер телефона",
        blank=True,
        null=True,
    )
    email = models.EmailField(verbose_name="email пользователя", blank=True)
    avatar = models.ImageField(
        upload_to="catalog/files/",
        null=True,
        validators=[validate_image],
        default="catalog/files/ava-default.png",
    )

    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    basket = models.ForeignKey(
        "Basket",
        on_delete=models.CASCADE,
        related_name="profile",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили пользователей"

    def __str__(self):
        return self.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.is_superuser:
        Profile.objects.create(user=instance)


class Sales(models.Model):
    product = models.ForeignKey(
        "Product", on_delete=models.CASCADE, verbose_name="товар"
    )
    shop = models.ForeignKey("Shop", on_delete=models.CASCADE, verbose_name="магазин")
    count = models.IntegerField(default=0, verbose_name="количество товара по скидке")
    dateFrom = models.DateField()
    dateTo = models.DateField()

    class Meta:
        verbose_name = "Распродажа"
        verbose_name_plural = "Распродажа"


class CategoryProduct(models.Model):  # категория товаров
    title = models.TextField(max_length=50, verbose_name="название категории")
    image = models.FileField(upload_to=create_image_path_for_category, null=True)
    slug = models.SlugField(blank=True, verbose_name="символьный код")
    tags = models.ManyToManyField(
        "TagsFile", related_name="tags_in_category", blank=True, null=True
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product_ref = models.ForeignKey(
        "Product", on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to=create_image_path_for_product_gallery)

    class Meta:
        verbose_name = "галерея изображений"
        verbose_name_plural = "галереи изображений"

    def save(self, *args, **kwargs):
        if not self.pk:
            self.image.open()
            self.image.seek(0)
            self.image.name = create_image_path_for_product_gallery(
                self, self.image.name
            )
        super().save(*args, **kwargs)


class Product(models.Model):  # товар
    category = models.ForeignKey(
        "CategoryProduct", on_delete=models.CASCADE, verbose_name="категория товара"
    )
    shop = models.ForeignKey(
        "Shop", on_delete=models.CASCADE, verbose_name="магазин товара"
    )
    specifications = models.ForeignKey(
        "Specifications", on_delete=models.CASCADE, verbose_name="спецификация товара"
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="цена товара"
    )
    count = models.IntegerField(default=0, verbose_name="количество ")
    date = models.DateField(auto_now_add=True)
    title = models.TextField(max_length=50, verbose_name="название товара")
    description = models.TextField(max_length=100, verbose_name="описание товара")
    big_text = models.TextField(
        verbose_name="большой текст для карточки товара", blank=True, null=True
    )
    free_delivery = models.BooleanField(default=True)
    product_picture = models.ImageField(
        upload_to=create_image_path_for_product, null=True, blank=True
    )
    rating = models.IntegerField(
        default=0, verbose_name="счетчик покупок данного товара"
    )
    reviews = models.IntegerField(
        default=0, verbose_name="счетчик просмотров данного товара"
    )
    tags = models.ManyToManyField("TagsFile", related_name="tags")
    slug = models.SlugField(unique=True, max_length=255, blank=True)
    limited_edition = models.BooleanField(
        default=False, verbose_name="ограниченный тираж"
    )
    gallery = models.ManyToManyField(ProductImage, blank=True, related_name="products")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return self.title

    def upper_reviews_product(self):
        self.reviews += 1
        self.save()


@receiver(pre_save, sender=Product)
def pre_save_product(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


class LimitedOffer(models.Model):
    """Отдельный класс для уникальных предложений.
    Тип message используется для вывода специального текста
    в слайдер на главной странице!"""

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="товар")
    new_price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="новая цена"
    )
    message = models.CharField(
        max_length=500, verbose_name="описание", blank=True, null=True
    )
    duration = models.DurationField(verbose_name="время до конца акции")
    created_at = models.DateTimeField(
        default=timezone.now, verbose_name="Дата создания"
    )

    class Meta:
        verbose_name = "Специальное предложение"
        verbose_name_plural = "Специальные предложения"


class TagsFile(models.Model):
    tags_name = models.TextField(max_length=50, verbose_name="тэг товара")

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

    def __str__(self):
        return self.tags_name


class Shop(models.Model):
    shop_name = models.TextField(max_length=50, verbose_name="название магазина")

    class Meta:
        verbose_name = "магазин"
        verbose_name_plural = "магазины"

    def __str__(self):
        return self.shop_name


class Reviews(models.Model):  # отзыв
    product = models.ForeignKey(
        "Product",
        on_delete=models.CASCADE,
        verbose_name="товар",
        related_name="product_title_product_set",
    )
    author = models.ForeignKey(
        "Profile", on_delete=models.CASCADE, verbose_name="пользователь"
    )
    text = models.CharField(
        default="Не указано", max_length=100, verbose_name="текст отзыва", blank=True
    )
    create_at = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    def __str__(self):
        return self.text


class Specifications(models.Model):
    name = models.TextField(max_length=50, verbose_name="название")
    value = models.TextField(max_length=50, verbose_name="значение")

    class Meta:
        verbose_name = "Спецификация"
        verbose_name_plural = "Спецификации"

    def __str__(self):
        return self.name


class OrderHistory(models.Model):
    user_order = models.ForeignKey(
        "Profile", on_delete=models.CASCADE, verbose_name="пользователь", null=True
    )
    product_order = models.ManyToManyField(Product, verbose_name="товары")
    payment_date = models.DateField(auto_now_add=True)
    delivery_type = models.TextField(
        max_length=30, default="не указан", verbose_name="способ доставки"
    )
    payment_type = models.TextField(
        max_length=30, default="не указан", verbose_name="способ оплаты"
    )
    total_cost = models.IntegerField(default=0, verbose_name="общая стоимость заказа")
    status = models.TextField(
        max_length=30, default="не указан", verbose_name="статус оплаты"
    )
    city = models.TextField(
        max_length=30, default="не указан", verbose_name="город доставки"
    )
    address = models.TextField(
        max_length=30, default="не указан", verbose_name="адрес доставки"
    )
    order = models.ManyToManyField("Order", verbose_name="заказы")
    products = models.ManyToManyField(
        Product,
        through="OrderedProduct",
        verbose_name="товары",
        related_name="products_with_quantity",
    )
    confirmed = models.BooleanField(default=False, verbose_name="Подтвержден")

my_store_app/forms.py
from django import forms
from my_store_app.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.db.models import Count
import random


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("text",)
        widgets = {
            "text": forms.Textarea(
                attrs={"class": "form-textarea", "placeholder": "Отзыв"}
            )
        }

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop("author", None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        review = super().save(commit=False)
        review.author = self.author
        if commit:
            review.save()
        return review


class SearchForm(forms.Form):
    keyword = forms.CharField(max_length=20, label="Искомое слово")
    products = forms.ModelChoiceField(
        queryset=Product.objects.all(), label="Товар", required=False
    )


class ProductFilterForm(forms.Form):
    expensive = forms.BooleanField(required=False)
    limited_edition = forms.BooleanField(required=False)
    min_price = forms.DecimalField(min_value=0, max_value=9999999999, required=False)
    max_price = forms.DecimalField(min_value=0, max_value=9999999999, required=False)
    tag = forms.ModelChoiceField(
        queryset=TagsFile.objects.all(),
        empty_label="Выберете тег с товарами",
        required=False,
    )
    count = forms.IntegerField(min_value=0, required=False, label="Количество товара")

api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from blog_app.models import Article, Theme
from .serializers import ArticleSerializer, ArticleDetailSerializer, ProductDetailSerializer
from rest_framework.generics import RetrieveAPIView
from rest_framework.pagination import PageNumberPagination
from my_store_app.models import Product, CategoryProduct
from .filters import ProductFilter, ArticleFilter
from rest_framework import filters
from django_filters import rest_framework as django_filters
from rest_framework import generics
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.permissions import AllowAny
from rest_framework.generics import GenericAPIView
from rest_framework.mixins import ListModelMixin, CreateModelMixin


class ArticleDetailView(RetrieveAPIView):
    queryset = Article.objects.all()
    serializer_class = ArticleDetailSerializer


class ProductListApiView(generics.ListAPIView):
    permission_classes = [AllowAny]
    serializer_class = ProductDetailSerializer
    queryset = Product.objects.all()
    filter_backends = [DjangoFilterBackend]
    filterset_class = ProductFilter


class ArticleListView(generics.ListAPIView):
    permission_classes = [AllowAny]
    serializer_class = ArticleDetailSerializer
    queryset = Article.objects.all()
    filter_backends = [DjangoFilterBackend]
    filterset_class = ArticleFilter

my_store_app/templates/my_store_app/api.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% if title %}
{{ title }}
{% else %}
{{ category.title }}
{% endif %}
{% endblock %}


{% block content %}
<h1>API</h1>
<p>
    Примеры представлений информации через API
</p>
<div>
    <ul>
        <li>
            <a href="{% url 'api:articles_api' %}">API списка статей</a>
        </li>
        <li>
            <a href="{% url 'api:article_api' pk=3%}">API одной статьи</a>
        </li>
        <li>
            <a href="{% url 'api:products_api' %}">API товаров</a>
        </li>
    </ul>
</div>
{% endblock %}

my_store_app/templates/my_store_app/index.html
{% extends "base.html" %}
{% load static %}



{% block content %}

<!-- Слайдер начало -->
<div class="Header-slider">
    <div class="Slider Slider_main">
        <div class="Slider-box">
            <!-- тестовый элемент -->
            {% for prod in slider_product %}
            <div class="Slider-item">
                <div class="Slider-content">
                    <div class="row">
                        <div class="row-block">
                            <strong class="Slider-title">{{ prod.title }}<span
                                    class="text_primary">&nbsp;{{prod.count}}</span><br>{{ prod.tags.first.tags_name }}
                            </strong>
                            <div class="Slider-text">
                                {{prod.description}}
                            </div>
                            <div class="Slider-footer"><a class="btn btn_primary"
                                                          href="{% url 'product' product_slug=prod.slug %}">Get
                                Started</a>
                            </div>
                        </div>
                        <div class="row-block">
                            <div class="Slider-img"><img src="{{prod.product_picture.url}}"
                                                         alt="{{prod.title}}"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- тестовый элемент -->

        </div>
        <div class="Slider-navigateWrap">
            <div class="Slider-navigate">
            </div>
        </div>
    </div>
</div>
<!-- Слайдер конец -->


<div class="Middle">
    <div class="Section">
        <div class="wrap">
            <!-- Банеры начало -->
            <div class="BannersHome">
                {% for ban in banners %}

                <a class="BannersHomeBlock" href="{% url 'category' category_slug=ban.slug %}">
                    <div class="BannersHomeBlock-row">
                        <div class="BannersHomeBlock-block">
                            <strong class="BannersHomeBlock-title">{{ban.title}}
                            </strong>
                            <div class="BannersHomeBlock-content">от&#32;<span class="BannersHomeBlock-price">{{ban.min_price}} руб.</span>
                            </div>
                        </div>
                        <div class="BannersHomeBlock-block">
                            <div class="BannersHomeBlock-img"><img src="{{ban.product_set.first.product_picture.url}}"
                                                                   alt="{{ban.title}}"/>
                            </div>
                        </div>
                    </div>
                </a>

                {%endfor%}
            </div>
            <!-- Банеры конец -->
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft Section_columnDesktop">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection Section-columnSection_mark">
                    <!-- Ограниченные предложения -->
                    <header class="Section-columnHeader">
                        <strong class="Section-columnTitle">ОГРАНИЧЕННЫЕ ПРЕДЛОЖЕНИЯ
                        </strong>
                    </header>
                    {% if limited_offer %}
                    <div class="Card"><a class="Card-picture"
                                         href="{% url 'product' product_slug=limited_offer.product.slug %}"><img
                            src="{{limited_offer.product.product_picture.url}}" alt="{{limited_offer.product.title}}"/></a>
                        <div class="Card-content">
                            <strong class="Card-title"><a href="{% url 'product' limited_offer.product.slug %}">{{limited_offer.product.title}}</a>
                            </strong>
                            <div class="Card-description">
                                <div class="Card-cost"><span
                                        class="Card-priceOld">{{limited_offer.product.price}} руб.</span><span
                                        class="Card-price">{{limited_offer.new_price}} руб.</span>
                                </div>
                                <div class="Card-category">{{limited_offer.product.category}}<br><span
                                        style="color: red">
                                    Осталось...
                                </span>
                                </div>
                            </div>
                            <div class="CountDown" data-date="{{now}}">
                                <div class="CountDown-block">
                                    <div class="CountDown-wrap">
                                        <div class="CountDown-days">
                                        </div>
                                        <span class="CountDown-label">Дней</span>
                                    </div>
                                </div>
                                <div class="CountDown-block">
                                    <div class="CountDown-wrap">
                                        <div class="CountDown-hours">
                                        </div>
                                        <span class="CountDown-label">Часов</span>
                                    </div>
                                </div>
                                <div class="CountDown-block">
                                    <div class="CountDown-wrap">
                                        <div class="CountDown-minutes">
                                        </div>
                                        <span class="CountDown-label">Минут</span>
                                    </div>
                                </div>
                                <div class="CountDown-block">
                                    <div class="CountDown-wrap">
                                        <div class="CountDown-secs">
                                        </div>
                                        <span class="CountDown-label">Секунд</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {%else%}
                    <div class="Card"><img
                            src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fcleanshop.ru%2Fcatalog%2Fsphd%2F5032475.html&psig=AOvVaw3uZygr1Tb1BtYkYzFLOVgz&ust=1682460233048000&source=images&cd=vfe&ved=0CA4QjRxqFwoTCJCpy4DDw_4CFQAAAAAdAAAAABAD"
                    />
                        <div class="Card-content">
                            <strong class="Card-title">Временно акций нет!
                            </strong>
                        </div>
                    </div>
                    {%endif%}

                    <!-- Ограниченные предложения -->
                </div>
            </div>
            <div class="Section-content">
                <header class="Section-header">
                    <h2 class="Section-title">Популярные товары
                    </h2>
                </header>
                <div class="Cards">
                    {% for prod in popular_product %}
                    <div class="Card"><a class="Card-picture" href="{% url 'product' product_slug=prod.slug %}"><img
                            src="{{prod.product_picture.url}}" alt="{{prod.title}}"/></a>
                        <div class="Card-content">
                            <strong class="Card-title"><a href="{% url 'product' product_slug=prod.slug %}">{{prod.title}}</a>
                            </strong>
                            <div class="Card-description">
                                <div class="Card-cost"><span class="Card-price">{{prod.price}} руб.</span>
                                </div>
                                <div class="Card-category">{{prod.category}}
                                </div>
                                {%if user%}
                                <div class="Card-hover"><a class="Card-btn"
                                                           href="{% url 'add-to-cart' product_id=prod.id %}"><img
                                        src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a>
                                </div>
                                {%else%}
                                <div class="Card-hover"><a class="Card-btn" href="#"><img
                                        src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a>
                                </div>
                                {%endif%}
                            </div>
                        </div>
                    </div>
                    {%endfor%}

                </div>
            </div>
        </div>
    </div>

    <div class="Section Section_column Section_columnRight">
        <div class="wrap">
            <div class="Section-content">
                <div class="Slider Slider_carousel">
                    <header class="Section-header Section-header_close">
                        <h2 class="Section-title">Ограниченный тираж
                        </h2>
                        <div class="Section-control">
                            <div class="Slider-navigate">
                            </div>
                        </div>
                    </header>
                    <div class="Slider-box Cards">
                        {% for card in limited_edition %}
                        <div class="Slider-item">
                            <div class="Slider-content">
                                <div class="Card"><a class="Card-picture"
                                                     href="{% url 'product' product_slug=card.slug %}"><img
                                        src="{{card.product_picture.url}}" alt="{{card.title}}"/></a>
                                    <div class="Card-content">
                                        <strong class="Card-title"><a href="{% url 'product' product_slug=card.slug %}">{{card.title}}</a>
                                        </strong>
                                        <div class="Card-description">
                                            <div class="Card-cost"><span class="Card-price">{{card.price}} руб.</span>
                                            </div>
                                            <div class="Card-category">{{card.category}}
                                            </div>
                                            {%if user%}
                                            <div class="Card-hover"><a class="Card-btn"
                                                                       href="{% url 'add-to-cart' product_id=card.id %}"><img
                                                    src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a>
                                            </div>
                                            {%else%}
                                            <div class="Card-hover"><a class="Card-btn" href="#"><img
                                                    src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a>
                                            </div>
                                            {%endif%}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}