api/urls.py
from django.contrib import admin
from django.urls import include, path
from blog_app.views import *
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'api'

urlpatterns = (
        [
            path('articles/<int:pk>', ArticleDetailView.as_view(), name='article_api'),
            path('articles/', ArticleListView.as_view(), name='articles_api'),
            path('products/', ProductListApiView.as_view(), name='products_api'),
        ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

blog_app/urls.py
from django.contrib import admin
from django.urls import include, path
from blog_app.views import *
from django.conf import settings
from django.conf.urls.static import static
from .views import CreateArticleView, ArticleListView, ArticleDetailView, ArticleThemeListView, UpdateArticleView

app_name = 'blog_app'

urlpatterns = [
                  path('update_article/<int:pk>/', UpdateArticleView.as_view(), name='update_article'),
                  path('theme/<slug:slug>/', ArticleThemeListView.as_view(), name='theme'),
                  path('create_article/', CreateArticleView.as_view(), name='create_article'),
                  path('', ArticleListView.as_view(), name='blog'),
                  path('<slug:slug>/', ArticleDetailView.as_view(), name='article'),

              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from my_store_app.views import *
from profile_app.views import *
from order_app.views import *
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path("admin/", admin.site.urls),
    path("", include("my_store_app.urls")),
    path("", include("profile_app.urls")),
    path("", include("order_app.urls")),
    path("blog/", include("blog_app.urls")),
    path("api/", include("api.urls")),

]

blog_app/models.py
from django.db import models
from django.db.models import Count
from my_store_app.models import Profile
from transliterate import slugify as make_slug


def create_image_path_for_article(instance, filename):
    return "upload/articles/article_{pk}/{filename}".format(
        pk=instance.pk, filename=filename
    )


class Theme(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(max_length=90, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = make_slug(self.title)
        super().save(*args, **kwargs)

    def count_articles(self):
        return self.articles.count()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Тема"
        verbose_name_plural = "Темы"



class Article(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=50000)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)
    date = models.DateField(auto_now_add=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE, related_name='articles')
    slug = models.SlugField(max_length=90, unique=True, blank=True)
    image = models.ImageField(upload_to=create_image_path_for_article, null=True, default=None, blank=True)
    rating = models.PositiveIntegerField(null=True, blank=True, default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = make_slug(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

    def count_rating(self):
        self.rating += 1

blog_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = (
            'title',
            'text',
            'author',
            'slug',
            'image',
            'theme',
        )

blog_app/views.py
from django.views.generic.list import ListView
from urllib import request
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView
from .forms import ArticleForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404

from .models import Article, Theme


class ArticleListView(ListView):
    model = Article
    context_object_name = 'articles'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        page = self.request.GET.get('page')

        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            articles = paginator.page(1)
        except EmptyPage:
            articles = paginator.page(paginator.num_pages)

        context = super().get_context_data(**kwargs)
        context['articles'] = articles
        context['themes'] = Theme.objects.all()
        return context


class ArticleThemeListView(View):

    def get(self, request, *args, **kwargs):
        theme_slug = kwargs.pop('slug', )
        theme = get_object_or_404(Theme, slug=theme_slug)
        articles = Article.objects.filter(theme=theme)
        title = theme.title

        context = {
            "articles": articles,
            "title": title,
        }

        return render(request, 'blog_app/article_list.html', context=context)


class ArticleDetailView(DetailView):
    model = Article

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.count_rating()
        self.object.save()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class CreateArticleView(LoginRequiredMixin, CreateView):
    template_name = 'blog_app/article_form.html'
    form_class = ArticleForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all()
        return context


class UpdateArticleView(LoginRequiredMixin, UpdateView):
    model = Article
    class_form = ArticleForm
    fields = ['slug', 'title', 'text', 'author', 'image', 'theme']
    success_url = '/blog/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['articles'] = Article.objects.all()
        return context

blog_app/templates/blog_app/article_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{article.title}}
{% endblock %}

{% block content %}
<h1>
    {{article.title}}
</h1>
{% if article.image %}
<div>
    <img src="{{article.image.url}}" width="500px">
</div>
{% endif %}
<br>
<div style="width: 1000px">
  {{article.text}}
</div>
<br>
<p>
    <a href="{% url 'blog_app:update_article' pk=article.pk %}">Редактировать статью</a>
</p>
{% endblock %}

blog_app/templates/blog_app/article_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if request.path|slice:"-15:" == 'create_article/' %}
Создание статьи
{%else%}
Обновление статьи
{%endif%}
{% endblock %}


{% block content %}
<h2>
    {% if request.path|slice:"-15:" == 'create_article/' %}
    Создание статьи
    {%else%}
    Обновление статьи
    {%endif%}
</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if request.path|slice:"-15:" == 'create_article/' %}
    <button type="submit">Создать статью</button>
    {% else %}
    <button type="submit">Обновить статью</button>
    {% endif %}
</form>
{% endblock %}

blog_app/templates/blog_app/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% if title %}
{{title}}
{%else%}
Блог
{%endif%}
{% endblock %}

{% block content %}
<h1>
    {% if title %}
    {{title}}
    {%else%}
    Блог
    {%endif%}
</h1>
<div class="Section-columnContent">

    {% for theme in themes %}
    <a class="btn btn_default btn_sm"
       style="background-color:DarkCyan; color: white; box-shadow: 10px 5px 5px LightSeaGreen; hover:"
       href="{% url 'blog_app:theme' slug=theme.slug %}">{{ theme.title }}</a>
    {% endfor %}

</div>
<br>

<br>
<div style="display:inline-block;">
    <ul>
        {% for article in articles %}
        <li>
            <div>

                <h3><a href="{% url 'blog_app:article' slug=article.slug %}">{{ article.title }}</a></h3>
                {% if article.image %}
                <a href="{% url 'blog_app:article' slug=article.slug %}">
                <img src="{{article.image.url}}" width="250px;"
                     style="border-radius: 10px; box-shadow: 5px 2px 8px LightSeaGreen; hover:">
                </a>
                {%else%}
                <a href="{% url 'blog_app:article' slug=article.slug %}">
                <img src="https://uprav.ru/upload/iblock/55b/55b9f1981bed718ca82445da3a4af634.jpg"
                     width="250px; border-radius:10px">
                </a>
                {%endif%}
            </div>
        </li>
        <br>
        {% empty %}
        <li>No articles yet.</li>
        {% endfor %}
    </ul>
</div>
{% if request.user.is_superuser or request.user.is_staff  %}
<div>
    <button style="background-color:RoyalBlue; border-radius:5px; margin-left:5px;"><a href="{% url 'blog_app:create_article'%}"><span style="color:white">Создать статью</span></a>
    </button>
</div>
{% endif %}

{% if page_obj.paginator.num_pages > 1 %}

<div class="Pagination">
    <div class="Pagination-ins">
        {% if page_obj.has_previous %}
        <a class="Pagination-element Pagination-element_prev"
           href="?page={{ page_obj.previous_page_number }}"><img
                src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/></a>
        {% else %}
        <a class="Pagination-element Pagination-element_prev Pagination-element_disabled"><img
                src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/></a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="Pagination-element Pagination-element_current" href="?page={{ num }}"><span
                class="Pagination-text">{{ num }}</span></a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="Pagination-element" href="?page={{ num }}"><span class="Pagination-text">{{ num }}</span></a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.next_page_number }}"><img
                src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/></a>
        {% else %}
        <a class="Pagination-element Pagination-element_prev Pagination-element_disabled"><img
                src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/></a>
        {% endif %}
    </div>
</div>
{% else %}
<br>
{% endif %}
{% endblock %}